services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  api:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - ./laundryOrdersApi:/app
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    command: dotnet run
    depends_on:
      - db

  front:
    build:
      context: ./laundryOrders
    volumes:
      - ./laundryOrders/:/app/
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    command: npm start -- --host 0.0.0.0
